"""change like_count to likes_count

Revision ID: 925a98ef47e6
Revises: f4b7d234d882
Create Date: 2025-12-26 22:09:04.470586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925a98ef47e6'
down_revision = 'f4b7d234d882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), nullable=False))
        batch_op.drop_column('like_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_count', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('likes_count')

    # ### end Alembic commands ###
